name: Build

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Apply pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  test-production:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run tests
        run: |
          pip install . -U
          pip install -r requirements-dev.txt
          python setup.py sdist
          pytest -vv --cov --profile
